version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres-db
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis-db:
    image: redis
    ports:
      - 6379:6379

  flask-app:
    build: .
    image: flask-postgres-image
    container_name: flask-app
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: 1234
      DB_HOST: postgres-db  
      DB_PORT: 5432
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis-db
    restart: always

volumes:
  postgres_data: